source "https://rubygems.org"

gem "rails", "~> 8.1.4"
gem "puma"
gem "jwt"
gem "pg"
gem "active_model_serializers", "~> 0.10.16"
gem "redis"
gem "rdkafka"
gem "sidekiq"

group :development, :test do
  gem "rspec-rails"
end
